title: Abhishek Bihani # your name (or website title) here
logo: "/images/ab pic2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. in Petroleum Engineering, UT Austin 
  <br><br>
  Computer Vision, Deep Learning and Computational Fluid Flow Researcher 
  <br><br>
  <a href="https://www.linkedin.com/in/abihani/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-150429209-1 # your Google Analytics tracking ID here
